version: "3.9"

services:
  web:
    build: .
    container_name: hoevelaken_autorooster
    ports:
      - "8000:8000"  # host:container
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
